kr1/kr1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myApp/', include('myApp.urls')),
]

kr1/myApp/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views


app_name = "myApp"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('catalogue/', views.catalogue, name='catalogue'),
    path('info/', views.info, name='info'),
    path('algorithm/', views.algorithm, name='algorithm'),
    path('about/', views.about, name='about'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kr1/myApp/models.py
from django.db import models

# Create your models here.

kr1/myApp/views.py
from django.shortcuts import render

# Create your views here.
def base(request):
    return render(request, 'base.html')

def home(request):
    return render(request, 'home.html')

def catalogue(request):
    bouquets = [
        {"image": "/static/catalogue1.jpg", "name": "Ранункулюсы", "price": "4950 р."},
        {"image": "/static/catalogue2.jpg", "name": "Букет 'Tiara'", "price": "5000 р."},
        {"image": "/static/catalogue3.jpg", "name": "Пионовидные розы", "price": "400 р./1 шт."},
        {"image": "/static/catalogue4.jpg", "name": "Пионы", "price": "500 р./1 шт."},
        {"image": "/static/catalogue5.jpg", "name": "Цветочная сумочка", "price": "7000 р."},
        {"image": "/static/catalogue6.jpg", "name": "Wow Букет", "price": "20000 р."},
        {"image": "/static/catalogue7.jpg", "name": "Тюльпаны", "price": "4000 р."},
        {"image": "/static/catalogue8.jpg", "name": "Букет 'Strawberry Coctail'", "price": "6200 р."},
        {"image": "/static/catalogue9.jpg", "name": "С пионами", "price": "5850 р."},
    ]

    context = {"bouquets": bouquets}
    return render(request, "catalogue.html", context)

def info(request):
    extras = {
        "Открытки": [
            {"name": "Открытка Улыбайся", "image": "/static/info1.jpg"},
            {"name": "Открытка - Рядом", "image": "/static/info2.jpg"},
            {"name": "Открытка - Весна", "image": "/static/info3.jpg"},
        ],
        "Вазы": [
            {"name": "Вазы стеклянные", "image": "/static/info4.jpg"},
            {"name": "Вазы керамические", "image": "/static/info5.jpg"},
            {"name": "Ваза - книга", "image": "/static/info6.jpg"},
        ],
        "Для домашнего ухода": [
            {"name": "Кензан", "image": "/static/info7.jpg"},
            {"name": "Секатор", "image": "/static/info8.jpg"},
            {"name": "Секатор-ножницы", "image": "/static/info9.jpg"},
        ],
    }

    context = {'extras': extras}
    return render(request, 'info.html', context)


def algorithm(request):
    result = None
    books_input = request.GET.get("books", "")

    if books_input:
        books_list = books_input.split(", ")

        books = []
        for book in books_list:
            try:
                name, pages = book.split("-")
                pages = int(pages)
                if pages < 200:
                    books.append((name, pages))
            except ValueError:
                pass

        books.sort(key=lambda x: (-x[1], x[0]))

        result = [book[0] for book in books]

    context = {"result": result}
    return render(request, "algorithm.html", context)



def about(request):
    student = {
        "name": "Хоменко Анастасия Максимовна",
        "photo": "/static/anastasia.jpg",
        "email": "amkhomenko_1@edu.hse.ru",
        "phone": "+79087270757",
    }

    program_description = """
    «Бизнес-информатика» представляет собой междисциплинарное направление, интегрирующее такие дисциплины, как 
    информатика, математика, экономика, менеджмент. По определению IEEE Conference on Business Informatics 
    «Бизнес-информатика представляет собой научное направление, ориентированное на изучение информационных процессов  
    и связанных с ними явлений в социально-экономическом и бизнес контексте…»
    """

    teachers = [
        {
            "name": "Улитин Борис Игоревич",
            "photo": "/static/ulitin.jpg",
            "email": "bulitin@hse.ru",
        },
        {
            "name": "Емельянова Мария Максимовна",
            "photo": "/static/emelyanova.jpg",
            "email": "example@hse.ru",
        }
    ]

    classmates = [
        {
            "name": "Лумбова Софья Игоревна",
            "photo": "/static/sofia.jpg",
            "email": "silumbova@edu.hse.ru",
            "phone": "+79038482926",
        },
        {
            "name": "Щапова Майя Алексеевна",
            "photo": "/static/maya.jpg",
            "email": "maschapova@edu.hse.ru",
            "phone": "+79200516002",
        }
    ]

    context = {
        "student": student,
        "program_description": program_description,
        "teachers": teachers,
        "classmates": classmates
    }

    return render(request, "about.html", context)

kr1/myApp/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center" style="color: #a4c700; margin-top: -70px;">Я и моя образовательная программа</h2>

    <div class="row mb-4">
        <div class="col-md-4 text-center">
            <img src="{{ student.photo }}" alt="Фото {{ student.name }}" class="img-fluid rounded shadow-sm" style="border-radius: 15px; max-height: 80%;">
        </div>
        <div class="col-md-8" style="margin-top: 20px;">
            <h3>{{ student.name }}</h3>
            <p><strong>Email:</strong> {{ student.email }}</p>
            <p><strong>Телефон:</strong> {{ student.phone }}</p>
            <h4>Бизнес-информатика</h4>
            <p>{{ program_description }}</p>
        </div>
    </div>

    <h3 class="text-center" style="color: #a4c700; margin-top: -80px;">Преподаватели</h3>
    <div class="row">
        {% for teacher in teachers %}
        <div class="col-md-6 mb-4">
            <div class="p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1;">
                <div class="text-center">
                    <img src="{{ teacher.photo }}" alt="Фото {{ teacher.name }}" class="img-fluid rounded shadow-sm" style="border-radius: 15px; max-height: 200px; max-width: 200px;">
                </div>
                <h5 class="text-center mt-2">{{ teacher.name }}</h5>
                <p class="text-center"><strong>Email:</strong> {{ teacher.email }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <h3 class="text-center mt-4" style="color: #a4c700;">Мои сокурсники</h3>
    <div class="row">
        {% for classmate in classmates %}
        <div class="col-md-6 mb-4">
            <div class="p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1;">
                <div class="text-center">
                    <img src="{{ classmate.photo }}" alt="Фото {{ classmate.name }}" class="img-fluid rounded shadow-sm" style="border-radius: 15px; max-height: 200px; max-width: 200px;">
                </div>
                <h5 class="text-center mt-2">{{ classmate.name }}</h5>
                <p class="text-center"><strong>Email:</strong> {{ classmate.email }}</p>
                <p class="text-center"><strong>Телефон:</strong> {{ classmate.phone }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

kr1/myApp/templates/algorithm.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center" style="color: #a4c700;">Фильтр книг по страницам</h2>
    <div>
        <p>Введите список книг в адресной строке браузера в следующем формате:</p>
        <pre>?books=Любимый сад-200, Как сдать ЕГЭ?-120</pre>
    </div>

    {% if result %}
    <h3 class="mt-4">Отсортированные книги:</h3>
    <div class="border p-3 rounded" style="background-color: #fff; border: 2px solid black;">
        {% for book in result %}
        <p>{{ book }}</p>
        {% endfor %}
    </div>
    {% else %}
    <p>Введите список книг в строке браузера, как показано выше.</p>
    {% endif %}
</div>
{% endblock %}

kr1/myApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Цветочный магазин</title>
    <link href="/static/styles.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f8d9e1;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'myApp:home' %}">
            <img src="{% static 'base.png' %}" alt="Logo" width="40" height="40">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Переключить навигацию">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse lead" id="navbarNav" >
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
                       href="{% url 'myApp:home' %}">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'catalogue' %}active{% endif %}"
                       href="{% url 'myApp:catalogue' %}">Каталог</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'info' %}active{% endif %}"
                       href="{% url 'myApp:info' %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Информация
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'myApp:info' %}">Доставка и оплата</a></li>
                        <li><a class="dropdown-item" href="#element2">Связаться с нами</a></li>
                        <li><a class="dropdown-item" href="#element3">Рекомендации по уходу</a></li>
                        <li><a class="dropdown-item" href="https://olacvetok.ru/" target="_blank">Наши партнеры</a></li>

                    </ul>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'algorithm' %}active{% endif %}"
                       href="{% url 'myApp:algorithm' %}">Алгоритмическая задача</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}"
                       href="{% url 'myApp:about' %}">О себе</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-5 pt-4">
    {% block content %}{% endblock %}
</div>

<div>
    {% block footer %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

kr1/myApp/templates/catalogue.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center" style="margin-top: -90px; color: #a4c700;">Каталог букетов</h2>
    <div class="row" style="margin-top: 20px;">
        {% for bouquet in bouquets %}
        <div class="col-md-4 mb-4">
            <div class="card border-white">
                <img src="{{ bouquet.image }}" class="card-img-top rounded" alt="{{ bouquet.name }}" style="border-radius: 15px;">
                <div class="card-body text-center">
                    <h5 class="card-title lead">{{ bouquet.name }}</h5>
                    <p class="card-text lead">Цена: {{ bouquet.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

kr1/myApp/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row align-items-center">
        <div class="col-md-6">
            <div class="p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1; margin-top: -67px;">
                <h1 class="fw-bold text-center" style="font-family: 'Georgia', serif;">Astro Flowers</h1>
                <h3 class="text-center" style="color: #a4c700;">цветочный салон</h3>
                <p class="mt-3 text-center lead" style="font-size: 15px;">
                    Самые свежие цветы со всего мира, для самых дорогих сердцу людей. <br>
                    Круглосуточная доставка букетов по Нижнему Новгороду!
                </p>
            </div>

            <div class="mt-3">
                <h2 class="text-center" style="color: #a4c700;">О нас</h2>
                <p class="lead">
                    Свежие цветы со всего мира, собранные с любовью, чтобы радовать самых дорогих сердцу людей.
                    Мы тщательно отбираем каждую композицию, сочетая природную красоту, стиль и элегантность.
                    Наши букеты передают искренние чувства, наполняя каждый момент теплотой и заботой.
                </p>
                <p class="lead">
                    Независимо от повода — будь то праздник, признание в любви или просто желание подарить улыбку —
                    у нас вы найдете идеальный букет, который оставит незабываемое впечатление.
                </p>
            </div>
        </div>
        <div class="col-md-6" style="margin-top: -40px; margin-bottom: 20px;">
            <img src="/static/home.jpg" alt="Букет" class="img-fluid rounded shadow-sm">
        </div>
    </div>
</div>
{% endblock %}

kr1/myApp/templates/info.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center" style="color: #a4c700; margin-top: -80px;" id="element1">Доставка и Оплата</h2>

    <div class="p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1; margin-top: 20px;">
        <p class="lead">
            <strong>Доставка букетов осуществляется круглосуточно.</strong><br>
            Среднее время доставки — 90 минут от оформления заказа. <br>
            <em>*Время доставки зависит от удаленности адреса и загруженности дорожного движения.</em><br>
            Доставка по городу Нижний Новгород от 450 рублей.<br>
            Исключение: особо отдаленные районы (7 микрорайон, аэропорт, Бор, отдаленные частные дома).<br>
            Информацию о доставке можно уточнить у флориста.<br>
            <strong>Рабочее время обработки заявок:</strong> с 9:00-21:00. Заказы после этого времени требуют подтверждения (необходимо позвонить флористу).
        </p>
        <p class="lead">
            <strong>Способы оплаты заказа:</strong>
            <ul class="lead">
                <li>Оплата через платежные системы: VISA, MasterCard, ApplePay, GooglePay и др.</li>
                <li>Оплата через расчетный счет для юр.лиц (предоставляем все необходимые документы).</li>
            </ul>
        </p>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <div class="p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1; margin-top: 35px;" >
                <h2 class="text-center" id="element2">Связаться с нами</h2>
                <p class="lead">
                    <strong>Телефон:</strong><br>
                    +7 (910) 790-45-35<br><br>
                    <strong>Адрес:</strong><br>
                    г. Н.Новгород, ул.Ильинская 31<br><br>
                    <strong>Режим работы:</strong><br>
                    Круглосуточно
                </p>
            </div>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center">
            <img src="/static/info.jpg" alt="Связаться с нами" class="img-fluid rounded shadow-sm" style="border-radius: 15px; max-width: 80%;">
        </div>
    </div>

    <div class="mt-4 p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1; margin-bottom: 20px;">
        <h2 class="text-center" id="element3">Уход за букетом</h2>
        <ol class="lead">
            <li><strong>Подготовка вазы:</strong>
                <ol>
                    <li>Налейте в чистую вазу прохладную воду.</li>
                </ol>
            </li>
            <li><strong>Подготовка стеблей:</strong>
                <ol>
                    <li>Уберите нижние листья со стеблей, чтобы они не находились в воде.</li>
                    <li>Освежите срезы растений, подержав их под проточной водой.</li>
                    <li>Используйте острый нож, делая срез под углом 45°.</li>
                </ol>
            </li>
            <li><strong>Ежедневный уход:</strong>
                <ol>
                    <li>Меняйте воду в вазе ежедневно.</li>
                    <li>Стебли необходимо обмывать под проточной водой.</li>
                    <li>Регулярно обновляйте срезы растений.</li>
                </ol>
            </li>
            <li><strong>Выбор места:</strong>
                <ol>
                    <li>Не ставьте вазу с букетом рядом с отопительными приборами.</li>
                    <li>Избегайте сквозняков и мест под прямыми солнечными лучами.</li>
                </ol>
            </li>
            <li><strong>Продление жизни цветов:</strong>
                <ol>
                    <li>Добавьте в воду специальные средства, такие как Chrysal или Floralife.</li>
                </ol>
            </li>
        </ol>
    </div>

    <div class="mt-4 p-4 border border-dark rounded shadow-sm" style="background-color: #f8d9e1;">
        <h2 class="text-center">Небольшие мелочи, которые могут Вам пригодиться</h2>

        {% for category, items in extras.items %}
            <h3 class="mt-4 text-center" style="color: #a4c700;">{{ category }}</h3>
            <div class="row">
                {% for item in items %}
                    <div class="col-md-4 text-center">
                        <img src="{{ item.image }}" alt="{{ item.name }}" class="img-fluid rounded shadow-sm" style="border-radius: 15px;  width: 250px; height: 300px;">
                        <p class="lead">{{ item.name }}</p>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #a4c700; margin-top: 40px;">
    <div class="container-fluid justify-content-center">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Переключить навигацию">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse lead" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#element1">Доставка и оплата</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#element2">Связаться с нами</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#element3">Уход за букетом</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}